### ISSUE TITLE
Error in Part II Ch VI?

### ISSUE THREAD

**Issue by siiky** [standardebooks/fyodor-dostoevsky_notes-from-underground_constance-garnett#4]
> Yes, Liza, one must first learn to live oneself before one blames others!”

The "live" can work, but sounds dubious to me... Seems to me "like" is more probable.

It's the same in Gutenberg: https://www.gutenberg.org/cache/epub/600/pg600-images.html

**Comment by acabal** [comment]
Also like this in print. You can check the page scans by looking at the ebook's homepage and clicking on the page scans link to confirm whether or not something is an error or not: https://standardebooks.org/ebooks/fyodor-dostoevsky/notes-from-underground/constance-garnett
